language: python
python:
  - "2.7"
  - "3.5"
cache:
  apt: true
  # TODO local node modules path correct?
  directories:
    - $HOME/.pip-cache/
    - $HOME/.tox
    - /home/travis/virtualenv/python2.7
before_script:
  - sudo apt-get install pypy
install:
  - echo 'Running installation in directory $PWD'
  - # Python
  - pip install -r dev-requirements.txt --cache-dir $HOME/.pip-cache

  - echo "Installed Python packages:"
  - pip freeze

script:
  - py.test
  - tox -e flake8

